# Dependabot configuration for automatic dependency updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  # Maintain dependencies for Cargo (Rust)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "rust"
    groups:
      rust-dependencies:
        patterns:
          - "*"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
